package moe.thisis.animecat;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.image.ImageView;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class UIController {
	@FXML
	private TableView animeTable;
	@FXML
	private TableColumn animeTitle;
	@FXML
	private TableColumn animeProgress;
	@FXML
	private TableColumn animeStatus;
	@FXML
	private ImageView metaCover;
	@FXML
	private Label metaTitle;
	@FXML
	private Label metaEpisodes;
	@FXML
	private Label metaYear;
	@FXML
	private Label metaStatus;
	@FXML
	private Label metaRating;
	@FXML
	private Button controlAdd;
	@FXML
	private Button controlSave;
	@FXML
	private Button controlQuit;
	@FXML
	private Button controlRemove;
	@FXML
	private ComboBox controlStatus;
	@FXML
	private Button controlProgressIncrement;

	// Event Listener on Button[#controlAdd].onAction
	@FXML
	public void entryAdd(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#controlSave].onAction
	@FXML
	public void listSave(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#controlQuit].onAction
	@FXML
	public void programQuit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#controlRemove].onAction
	@FXML
	public void entryRemove(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#controlProgressIncrement].onAction
	@FXML
	public void progressIncrement(ActionEvent event) {
		// TODO Autogenerated
	}
}
