package moe.thisis.animecat.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

import moe.thisis.animecat.Main;

import moe.thisis.animecat.model.Anime;

public class UIController {
	@FXML
	private TableView<Anime> animeTable;
	@FXML
	private TableColumn<Anime, String> animeTitleColumn;
	@FXML
	private TableColumn<Anime, String> animeIDColumn;
	@FXML
	private ImageView metaCover;
	@FXML
	private Label animeTitleLabel;
	@FXML
	private Label metaEpisodesLabel;
	@FXML
	private Label metaYearLabel;
	@FXML
	private Label metaStatusLabel;
	@FXML
	private Label metaRatingLabel;
	@FXML
	private Button controlAdd;
	@FXML
	private Button controlSave;
	@FXML
	private Button controlQuit;
	@FXML
	private Button controlRemove;

	// Event Listener on Button[#controlAdd].onAction
	@FXML
	public void entryAdd(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#controlSave].onAction
	@FXML
	public void listSave(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#controlQuit].onAction
	@FXML
	public void programQuit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#controlRemove].onAction
	@FXML
	public void entryRemove(ActionEvent event) {
		// TODO Autogenerated
	}
	
	private Main mainApp;
	
	public UIController() {
		
	}
	
	@FXML
	private void initialize() {
		animeTitleColumn.setCellValueFactory(cellData -> cellData.getValue().animeTitleProperty());
		animeIDColumn.setCellValueFactory(cellData -> cellData.getValue().animeIDProperty());
	}
	
	public void setMain(Main mainApp) {
		this.mainApp = mainApp;
		
		animeTable.setItems(mainApp.getAnimeData());
	}
	
	private void showAnimeDetails(Anime anime) {
		if (anime != null) {
			
		}
	}
}
